# Generated by Django 5.1.6 on 2025-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LBE', '0004_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
